server:
  port: 8081
  servlet:
    session:
      timeout: 1h
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/YJS_BB?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: wx623623
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
  web:
    resources:
      static-locations: classpath:static/
gorit:
  file:
    root:
      path: E:\Good_Project\JX_ShuangYiLiu\back\file
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.model


