server:
  tomcat:
    uri-encoding: utf-8
    basedir: /home/file_dir
  port: 8081
  servlet:
    session:
      timeout: 1h
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.110.156:3306/yjs_bb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: work@good114
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
  web:
    resources:
      static-locations: classpath:static/
gorit:
  file:
    root:
      path: /home/file_dir/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.model


